### ISSUE TITLE
Modify images having white background

### ISSUE THREAD

**Issue by PratyushSingh07** [coder2699/Dare2Change#22]
**Describe the feature you'd like**
When the app is set to Dark Mode there appears a white background as shown in the screenshots below 

**Screenshots**

![WhatsApp Image 2022-10-07 at 01 54 52](https://user-images.githubusercontent.com/90026952/194573815-16bac8c5-b7af-47ba-a9cf-2411e5d17837.jpeg)
![WhatsApp Image 2022-10-07 at 19 35 32](https://user-images.githubusercontent.com/90026952/194573889-75e2ad96-9794-4d7f-9d8f-f5987a4b9ce8.jpeg)

The Xml files where changes need to be made are : 
fragment_dashboard.xml
fragment_start_exercise.xml

**Comment by coder2699** [comment]
@PratyushSingh07 thanks for opening this issue. Get this issue resolved before starting issue #11 .

Please note:
- Carefully check the icons and images on all the screens.
- It will be better if you can find new images, with transparent bg (otherwise use same imgs with tranparent bg)
- In the second screenshot (dashboard one), I think its shadow color given & its not fault of image (do check it once). I don't think there's a need to change images there, just fix the shadow.

**Comment by coder2699** [comment]
@PratyushSingh07 in the Screenshot 2, 2nd exercise has white background with black dot intentionally, keep its white bg as it was..... every thing else is fine.

**Comment by PratyushSingh07** [comment]
> @PratyushSingh07 in the Screenshot 2, 2nd exercise has white background with black dot intentionally, keep its white bg as it was..... every thing else is fine.

ok, I have rectified it

**Comment by coder2699** [comment]
> > @PratyushSingh07 in the Screenshot 2, 2nd exercise has white background with black dot intentionally, keep its white bg as it was..... every thing else is fine.
> 
> ok, I have rectified it

Open a PR then, with these changes. Make sure no additional files are modified
